<?php

namespace CaboLabs\Debbie\PHPUnitTests;

use PHPUnit\Framework\TestCase as PHPUnitTestCase;

/**
 * Integration test: verifies the JUnit XML generated by Debbie's CLI.
 */
class JunitXmlBuilderTest extends PHPUnitTestCase
{
    private static string $projectRoot;
    private static string $resultsFile;
    private static \DOMDocument $xml;

    public static function setUpBeforeClass(): void
    {
        self::$projectRoot = dirname(__DIR__);
        self::$resultsFile = self::$projectRoot . DIRECTORY_SEPARATOR . 'test-results.xml';

        self::runCli([
            'tests',
            '-report=junit',
        ]);

        self::assertFileExists(self::$resultsFile, 'The CLI did not generate test-results.xml');

        $xml = new \DOMDocument();
        self::assertTrue($xml->load(self::$resultsFile), 'The CLI did not generate valid JUnit XML');
        self::$xml = $xml;
    }

    private static function runCli(array $arguments): void
    {
        $command = 'php cli.php ' . implode(' ', array_map('escapeshellarg', $arguments));
        $process = proc_open(
            $command,
            [
                0 => ['pipe', 'r'],
                1 => ['pipe', 'w'],
                2 => ['pipe', 'w'],
            ],
            $pipes,
            self::$projectRoot
        );

        fclose($pipes[0]);
        stream_get_contents($pipes[1]);
        stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        proc_close($process);
    }

    private function findTestCase(string $suiteName, string $testName): \DOMElement
    {
        foreach (self::$xml->getElementsByTagName('testsuite') as $testsuite) {
            if ($testsuite->getAttribute('name') !== $suiteName) {
                continue;
            }

            foreach ($testsuite->getElementsByTagName('testcase') as $testcase) {
                if ($testcase->getAttribute('name') === $testName) {
                    return $testcase;
                }
            }
        }

        $this->fail("Test case \"$testName\" not found in suite \"$suiteName\"");
    }

    /**
     * Verifies the XML details of a  passing Debbie test.
     * Expect: the testcase has its name, classname, and captured output.
     */
    public function testPassingTestCaseContainsExpectedXmlDetails(): void
    {
        $testcase = $this->findTestCase(
            'tests\\suite1\\TestCase11',
            'test_this_is_a_test'
        );

        $this->assertSame('tests\\suite1\\TestCase11', $testcase->getAttribute('classname'));
        $this->assertSame('this is a test output', $testcase->getElementsByTagName('system-out')->item(0)->textContent);
        $this->assertCount(0, $testcase->getElementsByTagName('failure'));
        $this->assertCount(0, $testcase->getElementsByTagName('error'));
    }

    /**
     * Verifies the XML details of a Debbie test with an assertion failure.
     * Expect: the testcase contains the actual failure message and type.
     */
    public function testFailureContainsExpectedXmlDetails(): void
    {
        $testcase = $this->findTestCase(
            'tests\\suite5\\TestCase53',
            'test_this_is_another_test_53'
        );
        $failure = $testcase->getElementsByTagName('failure')->item(0);

        $this->assertSame('This is happening', $failure->getAttribute('message'));
        $this->assertSame('AssertionFailure', $failure->getAttribute('type'));
    }

    /**
     * Verifies the XML details of a  Debbie test with a runtime error.
     * Expect: the testcase contains the actual runtime error message and type.
     */
    public function testErrorContainsExpectedXmlDetails(): void
    {
        $testcase = $this->findTestCase(
            'tests\\suite5\\TestCase51',
            'test_warning'
        );
        $error = $testcase->getElementsByTagName('error')->item(0);

        $this->assertSame('This is an intentional warning', $error->getAttribute('message'));
        $this->assertSame('RuntimeError', $error->getAttribute('type'));
    }

    /**
     * Verifies that the XML builder records output from a  Debbie test.
     * Expect: the  output is preserved in a system-out element.
     */
    public function testTestOutputIsIncludedInTheXml(): void
    {
        $testcase = $this->findTestCase(
            'tests\\suite2\\TestCase22',
            'test_this_is_a_test'
        );

        $this->assertSame('this is a test output', $testcase->getElementsByTagName('system-out')->item(0)->textContent);
    }

    /**
     * Verifies that the CLI can generate XML for one  test case.
     * Expect: the report contains only TestCase11 and its three  tests.
     */
    public function testCliCanGenerateXmlForAnIndividualTestCase(): void
    {
        $fullReport = self::$xml->saveXML();

        try {
            self::runCli([
                'tests',
                'suite1',
                'TestCase11',
                '-report=junit',
            ]);

            $xml = new \DOMDocument();
            $this->assertTrue($xml->load(self::$resultsFile), 'The CLI did not generate valid JUnit XML');

            $testsuites = $xml->getElementsByTagName('testsuites')->item(0);
            $this->assertSame('3', $testsuites->getAttribute('tests'));
            $this->assertSame('1', $testsuites->getAttribute('failures'));
            $this->assertSame('0', $testsuites->getAttribute('errors'));
            $this->assertCount(1, $xml->getElementsByTagName('testsuite'));
            $this->assertSame(
                'tests\\suite1\\TestCase11',
                $xml->getElementsByTagName('testsuite')->item(0)->getAttribute('name')
            );
        } finally {
            file_put_contents(self::$resultsFile, $fullReport);
        }
    }
}
